spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sifra
    driverClassName : com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
#      ddl-auto: create-drop
    database-platform : org.hibernate.dialect.MySQL5Dialect 
    
server:
  port: 8088
  ssl:
    enabled: true
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: bc
    trust-store: ${KEY_STORE_CLASSPATH_TRUST}
    trust-store-password: ${KEY_STORE_TRUST_PASSWORD}         
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}

proba: "Update"

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]