spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sifra
    driverClassName : com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
    database-platform : org.hibernate.dialect.MySQL5Dialect  
    
server:
  port: 8095
  

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#eureka:
#  client:
#    enabled: true
#    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
#    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
#  instance:
#    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
#    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance

user-email: "nikola@yahoo.com" 

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]